apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: nodejs
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

