

# this file label is changed (nodejs1) and for secret file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app2
  labels:
    app: nodejs1
    namespace: project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs1
  template:
    metadata:
      labels:
        app: nodejs1
    spec:
      containers:
      - name: nodejs-container
        image: sanjanathamke/todonode:latest
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
