apiVersion: v1
kind: Service
metadata:
  name: my-service-load
  namespace: project
spec:
  selector:
    app: nodejs
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer 
