apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded value for "admin"
  password: cGFzc3dvcmQxMjM=  # base64 encoded value for "password123"
